In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import(
LabelEncoder,
OneHotEncoder,
OrdinalEncoder,
TargetEncoder,
StandardScaler,
MinMaxScaler,
RobustScaler,
MaxAbsScaler
)

In [3]:
df = pd.read_csv('ds_salaries.csv')
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

In [5]:
df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [6]:
df.sample(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
158,2023,MI,FT,Data Analyst,35000,GBP,42533,GB,0,GB,M
1362,2023,SE,FT,Machine Learning Engineer,163800,USD,163800,US,0,US,M
503,2023,SE,FT,Data Engineer,230000,USD,230000,US,0,US,M
436,2023,SE,FT,Data Scientist,170000,USD,170000,US,100,US,M
3042,2022,MI,FT,Data Engineer,24000,USD,24000,US,0,US,M

In [7]:
df.shape

(3755, 11)

In [8]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           3755 non-null   int64
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB

In [10]:
df.describe()

         work_year        salary  salary_in_usd  remote_ratio
count  3755.000000  3.755000e+03    3755.000000   3755.000000
mean   2022.373635  1.906956e+05  137570.389880     46.271638
std       0.691448  6.716765e+05   63055.625278     48.589050
min    2020.000000  6.000000e+03    5132.000000      0.000000
25%    2022.000000  1.000000e+05   95000.000000      0.000000
50%    2022.000000  1.380000e+05  135000.000000      0.000000
75%    2023.000000  1.800000e+05  175000.000000    100.000000
max    2023.000000  3.040000e+07  450000.000000    100.000000

In [11]:
df.describe(include='object')

,experience_level,employment_type,job_title,salary_currency,employee_residence,company_location,company_size
count,3755,3755,3755,3755,3755,3755,3755
unique,4,4,93,20,78,72,3
top,SE,FT,Data Engineer,USD,US,US,M
freq,2516,3718,1040,3224,3004,3040,3153

In [12]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [13]:
df.isna().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(1171)

In [15]:
df = df.drop_duplicates()

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print("-"*50)

work_year
4
[2023 2022 2020 2021]
--------------------------------------------------
experience_level
4
['SE' 'MI' 'EN' 'EX']
--------------------------------------------------
employment_type
4
['FT' 'CT' 'FL' 'PT']
--------------------------------------------------
job_title
93
['Principal Data Scientist' 'ML Engineer' 'Data Scientist'
 'Applied Scientist' 'Data Analyst' 'Data Modeler' 'Research Engineer'
 'Analytics Engineer' 'Business Intelligence Engineer'
 'Machine Learning Engineer' 'Data Strategist' 'Data Engineer'
 'Computer Vision Engineer' 'Data Quality Analyst'
 'Compliance Data Analyst' 'Data Architect'
 'Applied Machine Learning Engineer' 'AI Developer' 'Research Scientist'
 'Data Analytics Manager' 'Business Data Analyst' 'Applied Data Scientist'
 'Staff Data Analyst' 'ETL Engineer' 'Data DevOps Engineer' 'Head of Data'
 'Data Science Manager' 'Data Manager' 'Machine Learning Researcher'
 'Big Data Engineer' 'Data Specialist' 'Lead Data Analyst'
 'BI Data Engineer' 'Director of Data Science'
 'Machine Learning Scientist' 'MLOps Engineer' 'AI Scientist'
 'Autonomous Vehicle Technician' 'Applied Machine Learning Scientist'
 'Lead Data Scientist' 'Cloud Database Engineer' 'Financial Data Analyst'
 'Data Infrastructure Engineer' 'Software Data Engineer' 'AI Programmer'
 'Data Operations Engineer' 'BI Developer' 'Data Science Lead'
 'Deep Learning Researcher' 'BI Analyst' 'Data Science Consultant'
 'Data Analytics Specialist' 'Machine Learning Infrastructure Engineer'
 'BI Data Analyst' 'Head of Data Science' 'Insight Analyst'
 'Deep Learning Engineer' 'Machine Learning Software Engineer'
 'Big Data Architect' 'Product Data Analyst'
 'Computer Vision Software Engineer' 'Azure Data Engineer'
 'Marketing Data Engineer' 'Data Analytics Lead' 'Data Lead'
 'Data Science Engineer' 'Machine Learning Research Engineer'
 'NLP Engineer' 'Manager Data Management' 'Machine Learning Developer'
 '3D Computer Vision Researcher' 'Principal Machine Learning Engineer'
 'Data Analytics Engineer' 'Data Analytics Consultant'
 'Data Management Specialist' 'Data Science Tech Lead'
 'Data Scientist Lead' 'Cloud Data Engineer' 'Data Operations Analyst'
 'Marketing Data Analyst' 'Power BI Developer' 'Product Data Scientist'
 'Principal Data Architect' 'Machine Learning Manager'
 'Lead Machine Learning Engineer' 'ETL Developer' 'Cloud Data Architect'
 'Lead Data Engineer' 'Head of Machine Learning' 'Principal Data Analyst'
 'Principal Data Engineer' 'Staff Data Scientist' 'Finance Data Analyst']
--------------------------------------------------
salary
815
[   80000    30000    25500   175000   120000   222200   136000   219000
   141000   147100    90700   130000   100000   213660   130760   170000
   150000   110000   275000   174000   230000   143200   225000   156400
   200000    90000    72000   253200   342810   184590   162500   105380
    64500  1650000   204620   110680   270703   221484   212750   185000
   262000   245000   275300   183500   218500   199098   203300   123600
   189110   139000   258750   231500   166000   172500   110500   238000
   176000   237000   201450   309400   159100   115000    81500   280000
   210000   280100   168100   193500   510000    65000   300000   185900
   129300   140000    45000    36000   105000    70000   163196   145885
   217000   202800   104300   145000   165000   132300   179170    94300
   152500   116450   247300   133800   203000   133000   220000    54000
   289800   214000   179820   143860   283200   188800   214200   252000
   129000   155000   161800   141600   342300   176100    85000   138784
    83270    75000   204500   138900   318300   212200    95000   195000
   160000  1700000    38000    35000   168400   105200   190000   241000
    55000    15000    47500   250000   228000   186000   180000    50000
   205000   215000   247500   172200   224000  1400000   128000   329500
   269600   203500   152000   239000   122900   191765   134236   112000
    84000   135000   105500   293000   148500   240500   123700   152900
   117100   173000   113000   260000   184000   149500   127075   219535
   146115   199000   162000   221000   153000   187000   179000   109000
   142000   198800   125000    86000   106000   280700   150450   250500
   159500   130001    71907    93918    51962   257000   147000   222000
   133200   156000   304000   161200    84570   240000   183600   289076
   202353   157750   104650    68000    60000   181000   154000   146000
    64200    56100   208450   170550   171250   113750   153600   100500
   182500   121500   203100   114500    92700    61800   258000   167500
   106500    57000   286000   207000   223250   178600   353200   249300
   297300   198200   151800   317070   170730    20000   108000   134000
   124000   124500   148700   125600   120250   183000  1500000   216000
   143865   115092   132000   208049   128500   149600   102000   106800
   151000     7000    40000   143000    42000   111000   265000   235000
    60400   164000    56000    83500    52500   201036   134024    62000
    58000   172000   163800   126000   139500   109400   205600   105700
   239748   159832   186300   102500   149040   113900   172600   107900
   180180   106020   376080   213120   206500   121600   194500   115500
   115934    81666   206000   138000    92000    48000    87000   299500
   245100   115100    73900   141288    94192   210914   116704   185700
   169000   110600   193000   136850   276000   178500   161000    83300
   112700   128750   106250   188500   117000   104500   127000    94000
   210550   153300   161500   119500   148750   146300   153400   122700
   123900   340000   121700   310000   149076    82365    85500    97750
   201000   122000   116990    82920   142200   205920   171600    78000
   116000    36050    34320    93800    67000  1300000  1000000   104000
   152380   121904   128280   106900   192000   170500    60027    44737
   131899   104891   124740    65488    72200    64980   179975    86466
   168000   167580    87980   202000   148000   269000   158000   197000
   290000   172800   300240   200160   370000   137500   323300   184700
   153088   183310   144000    66000   126277   126500   272000   259000
   101400   288000   215050   198000   114000   209300   182200   227000
    52000   226700   133300   124999   800000    63000   253750   169200
   213580   163625    12000   375000  1350000   231250   138750   284310
   153090   225900   385000    93919   241871   133832   192500   216100
   140800   284000   236000   248100   145900   155850   102544   151410
   115360  1050000    25000   107000    23000   182750   314100   195800
   350000   262500   209450   158677   103200    61200    59000   174500
   107250   119000   285800   154600  5000000   124234    74540    79000
   141290    74178   107500  1060000     6000  1440000   840000  1250000
   182000   234100   223800   172100   232200   167200   291500   196200
   150900   167000    96100   196000   126100   187500    24000   165750
    89700    55250   175308   100706   229000  4000000   272550    64000
   143100   180560   115440  1125000   261500   134500  1100000    94500
   127500    51000   248400  4460000   149000   246000    10000  2500000
  2800000   249500   149850   122500   102640    66100   122600   159000
   255000   166700   194000   129400    89200   178750   197430   134760
    99000   105120    75360   171000    13000   213000   227200    61000
   243000   178000    96000   137000   189750   140250   191200   179500
    26000   118000   177000   131000   193750   116250   208000    45555
  6600000   140700    33000   154560   123648   177500   192564   144854
   179305   142127   315000   243900   156600    77300    45600   184100
   198440    47000   187200   116100   159699   138938    76000   125404
   123000    92250    97000   157000   345600   230400   175950   130050
   236600    27000   400000     8000   123400    88100   139600    85700
    98200    98000   144200  3000000   188700   160395   191475   141525
   156868   178800   132100   229998   154545    99750    68400   236900
   159200   243225   179775   218000   145300   195400   131300   195700
   130500   141300   102100    83000  1800000   633000   179400   193900
   222640   182160   297500    93000    73000    40300   136994   101570
    97500   212800   142800   500000   130240    83376    65004    84958
    66822    81000    46000   204100   136100     7500    77000    28500
   119300   146200   124270   185800   137400   148800  7500000    82000
    32400   216200   144100   175100   189650   164996    99450   188100
   139860   248700   167100   450000   189500   140100   177600   202900
   900000  4200000   260500    73400    49500  2400000   206699    99100
   221300    74000   249260   185400   128875    93700   136260   109280
   150075   110925    22800   112900    90320    62500   105400    43200
   215300   158200   209100   165400   132320   208775   147800  6000000
   100800   140400    82900    63900   112300   108800   242000   165220
   120160   124190   181940   220110   160080   106260   120600    84900
   136620    99360   161342   137141   211500   138600   192400    61300
    95550   136600   167875   205300   200100    70500   116150    99050
   192600   266400   150260    69000   324000   185100   104890    53000
    88000    66500   121000    29000    69999    52800   405000   380000
  8500000  7000000    38400    82500   700000     8760    51999    41000
    13400   103000   270000    45760    44000  2250000    37456 11000000
    14000  2200000   188000  2100000    51400    61500   720000    31000
    91000  1600000   256000    72500    65720   111775    93150    21600
  4900000  1200000    21000  1799997     9272   120500    21844    22000
    76760  1672000   420000 30400000    32000   416000    40900  4450000
   423000   325000    34000    69600   435000    37000    19000    18000
    39600  1335000  1450000   190200   138350   130800   412000]
--------------------------------------------------
salary_currency
20
['EUR' 'USD' 'INR' 'HKD' 'CHF' 'GBP' 'AUD' 'SGD' 'CAD' 'ILS' 'BRL' 'THB'
 'PLN' 'HUF' 'CZK' 'DKK' 'JPY' 'MXN' 'TRY' 'CLP']
--------------------------------------------------
salary_in_usd
1035
[ 85847  30000  25500 ...  28369 412000  94665]
--------------------------------------------------
employee_residence
78
['ES' 'US' 'CA' 'DE' 'GB' 'NG' 'IN' 'HK' 'PT' 'NL' 'CH' 'CF' 'FR' 'AU'
 'FI' 'UA' 'IE' 'IL' 'GH' 'AT' 'CO' 'SG' 'SE' 'SI' 'MX' 'UZ' 'BR' 'TH'
 'HR' 'PL' 'KW' 'VN' 'CY' 'AR' 'AM' 'BA' 'KE' 'GR' 'MK' 'LV' 'RO' 'PK'
 'IT' 'MA' 'LT' 'BE' 'AS' 'IR' 'HU' 'SK' 'CN' 'CZ' 'CR' 'TR' 'CL' 'PR'
 'DK' 'BO' 'PH' 'DO' 'EG' 'ID' 'AE' 'MY' 'JP' 'EE' 'HN' 'TN' 'RU' 'DZ'
 'IQ' 'BG' 'JE' 'RS' 'NZ' 'MD' 'LU' 'MT']
--------------------------------------------------
remote_ratio
3
[100   0  50]
--------------------------------------------------
company_location
72
['ES' 'US' 'CA' 'DE' 'GB' 'NG' 'IN' 'HK' 'NL' 'CH' 'CF' 'FR' 'FI' 'UA'
 'IE' 'IL' 'GH' 'CO' 'SG' 'AU' 'SE' 'SI' 'MX' 'BR' 'PT' 'RU' 'TH' 'HR'
 'VN' 'EE' 'AM' 'BA' 'KE' 'GR' 'MK' 'LV' 'RO' 'PK' 'IT' 'MA' 'PL' 'AL'
 'AR' 'LT' 'AS' 'CR' 'IR' 'BS' 'HU' 'AT' 'SK' 'CZ' 'TR' 'PR' 'DK' 'BO'
 'PH' 'BE' 'ID' 'EG' 'AE' 'LU' 'MY' 'HN' 'JP' 'DZ' 'IQ' 'CN' 'NZ' 'CL'
 'MD' 'MT']
--------------------------------------------------
company_size
3
['L' 'S' 'M']
--------------------------------------------------