Multiple machine learning models are combined together to make predictions.

Improve accuracy, better predictions, gives more reliable results than a single model.

### Types

Bagging(Bootstrap Aggregation)

Boosting

Both can be used for classification and regression.

### Basic idea of Bagging

Multiple models are trained.

Each model receives a different sample of the dataset.

All models work independently.

Their outputs are combined to produce the final prediction.

### Components of Bagging

Dataset

Base Learners (Multiple models used by bagging)

### Training Process

Step 1 : Create dataset samples. (Different sample taken from training dataset, Each sample given to different model).

Step 2 : Train Models

Step 3 : Make Predictions (Each model predicts separately).

Final Prediction in Classification (Majority Voting Classifier)

Final Prediction in Regression (Average of all Outputs)

In [ ]:
# Important characteristic of Bagging (Parallel Training --> All models are trained at the same time)

### Boosting (Main Idea)

Multiple weak learners are combined.

Models are connected sequentially.

Each models tries to improve the mistakes made by previous model.

Together they form a strong learner.

### Training Process

Step 1 : Give the entire dataset to Model 1. (Model 1 trains and makes predictions.)

Step 2 : Model 1 makes some mistakes.

Step 3 : Those incorrectly predicted recoreds are passed to Model 2 along with some additional records which are correct.

Step 4 : Model 2 learns from those mistakes. It also makes some errors. Those erros are passed to Model 3.

Step 5 : The process continues (M1 -> M2 -> M3 -> ..... -> Mn)

Each new model focuses on correcting previous mistakes.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib
import warnings
warnings.filterwarnings('ignore')

In [15]:
# Loading data
df = pd.read_csv('cardekho.csv')
# print(f'Rows : {df.shape[0]}')
# print(f'Columns : {df.shape[1]}')

In [5]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [16]:
df.tail()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [6]:
df.shape

(15411, 14)

In [7]:
print('Column data types:')
print(df.dtypes)

Column data types:
Unnamed: 0             int64
car_name              object
brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [8]:
df.sample()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
6750,8613,Maruti Swift,Maruti,Swift,4,59000,Dealer,Diesel,Manual,28.4,1248,74.0,5,700000

In [9]:
df.drop(columns=['Unnamed: 0', 'car_name', 'model'], inplace= True)
print('Dropped Unnecessary columns.')

Dropped Unnecessary columns.

In [10]:
df.sample()

,brand,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
7658,Renault,5,42000,Dealer,Petrol,Manual,25.17,799,53.3,5,295000

In [19]:
print('Missing values per columns: ')
df.isna().sum()

Missing values per columns:

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [21]:
before = len(df)
df.dropna(inplace=True)
after = len(df)
print(f'Removed {before - after}  rows containing missing values.')
print(f'Dataset now has {after} rows')

Removed 0  rows containing missing values.
Dataset now has 15411 rows