In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('DataSet/fifa_eda_stats.csv')

In [4]:
df.sample(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
17768,246331,H. Hauso,17,Norway,52,68,Vålerenga Fotball,€90K,€1K,Right,...,43.0,50.0,58.0,54.0,10.0,14.0,13.0,12.0,14.0,€169K
12643,205972,R. Bentancourt,25,Uruguay,63,68,Independiente Santa Fe,€500K,€1K,Right,...,59.0,35.0,14.0,12.0,7.0,7.0,13.0,14.0,6.0,€738K
13814,223963,C. Humphreys-Grant,19,England,62,77,Manchester City,€600K,€6K,Right,...,46.0,61.0,65.0,58.0,7.0,14.0,16.0,12.0,6.0,€1.5M
6063,205941,C. Chávez,31,Argentina,69,69,Club Atlético Aldosivi,€925K,€7K,Right,...,67.0,24.0,32.0,24.0,9.0,14.0,11.0,12.0,13.0,€1.3M
7072,201841,N. Dussenne,26,Belgium,68,71,Royal Excel Mouscron,€925K,€5K,Right,...,69.0,70.0,69.0,66.0,12.0,16.0,15.0,7.0,11.0,€1.4M

In [12]:
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [13]:
df.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,Right,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,Right,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,241638,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,Right,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,Right,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,Right,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [5]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Weak Foot', 'Skill Moves', 'Work Rate', 'Body Type', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause'],
      dtype='object')

In [7]:
df.shape

(18207, 57)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     18207 non-null  object
 8   Wage                      18207 non-null  object
 9   Preferred Foot            18159 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Weak Foot                 18159 non-null  float64
 12  Skill Moves               18159 non-null  float64
 13  Work Rate                 18159 non-null  object
 14  Body Type                 18159 non-null  object
 15  Position                  18147 non-null  object
 16  Jersey Number             18147 non-null  float64
 17  Joined                    16654 non-null  object
 18  Loaned From               1264 non-null   object
 19  Contract Valid Until      17918 non-null  object
 20  Height                    18159 non-null  object
 21  Weight                    18159 non-null  object
 22  Crossing                  18159 non-null  float64
 23  Finishing                 18159 non-null  float64
 24  HeadingAccuracy           18159 non-null  float64
 25  ShortPassing              18159 non-null  float64
 26  Volleys                   18159 non-null  float64
 27  Dribbling                 18159 non-null  float64
 28  Curve                     18159 non-null  float64
 29  FKAccuracy                18159 non-null  float64
 30  LongPassing               18159 non-null  float64
 31  BallControl               18159 non-null  float64
 32  Acceleration              18159 non-null  float64
 33  SprintSpeed               18159 non-null  float64
 34  Agility                   18159 non-null  float64
 35  Reactions                 18159 non-null  float64
 36  Balance                   18159 non-null  float64
 37  ShotPower                 18159 non-null  float64
 38  Jumping                   18159 non-null  float64
 39  Stamina                   18159 non-null  float64
 40  Strength                  18159 non-null  float64
 41  LongShots                 18159 non-null  float64
 42  Aggression                18159 non-null  float64
 43  Interceptions             18159 non-null  float64
 44  Positioning               18159 non-null  float64
 45  Vision                    18159 non-null  float64
 46  Penalties                 18159 non-null  float64
 47  Composure                 18159 non-null  float64
 48  Marking                   18159 non-null  float64
 49  StandingTackle            18159 non-null  float64
 50  SlidingTackle             18159 non-null  float64
 51  GKDiving                  18159 non-null  float64
 52  GKHandling                18159 non-null  float64
 53  GKKicking                 18159 non-null  float64
 54  GKPositioning             18159 non-null  float64
 55  GKReflexes                18159 non-null  float64
 56  Release Clause            16643 non-null  object
dtypes: float64(38), int64(4), object(15)
memory usage: 7.9+ MB

In [9]:
df.describe()

,ID,Age,Overall,Potential,International Reputation,Weak Foot,Skill Moves,Jersey Number,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,18159.000000,18159.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,214298.338606,25.122206,66.238699,71.307299,1.113222,2.947299,2.361308,19.546096,49.734181,45.550911,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,29965.244204,4.669943,6.908930,6.136496,0.394031,0.660456,0.756164,15.947765,18.364524,19.525820,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,16.000000,16.000000,46.000000,48.000000,1.000000,1.000000,1.000000,1.000000,5.000000,2.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,200315.500000,21.000000,62.000000,67.000000,1.000000,3.000000,2.000000,8.000000,38.000000,30.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,221759.000000,25.000000,66.000000,71.000000,1.000000,3.000000,2.000000,17.000000,54.000000,49.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,236529.500000,28.000000,71.000000,75.000000,1.000000,3.000000,3.000000,26.000000,64.000000,62.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,246620.000000,45.000000,94.000000,95.000000,5.000000,5.000000,5.000000,99.000000,93.000000,95.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [15]:
df.describe(include='object')

,Name,Nationality,Club,Value,Wage,Preferred Foot,Work Rate,Body Type,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause
count,18207,18207,17966,18207,18207,18159,18159,18159,18147,16654,1264,17918,18159,18159,16643
unique,17194,164,651,217,144,2,9,10,27,1736,341,36,21,57,1244
top,J. Rodríguez,England,FC Barcelona,€1.1M,€1K,Right,Medium/ Medium,Normal,ST,"Jul 1, 2018",Atalanta,2019,6'0,165lbs,€1.1M
freq,11,1662,33,431,4900,13948,9810,10595,2152,1538,20,4819,2881,1483,557

In [17]:
df.describe(include='int64')

                  ID           Age       Overall     Potential
count   18207.000000  18207.000000  18207.000000  18207.000000
mean   214298.338606     25.122206     66.238699     71.307299
std     29965.244204      4.669943      6.908930      6.136496
min        16.000000     16.000000     46.000000     48.000000
25%    200315.500000     21.000000     62.000000     67.000000
50%    221759.000000     25.000000     66.000000     71.000000
75%    236529.500000     28.000000     71.000000     75.000000
max    246620.000000     45.000000     94.000000     95.000000

In [18]:
df.isna().sum()

ID                              0
Name                            0
Age                             0
Nationality                     0
Overall                         0
Potential                       0
Club                          241
Value                           0
Wage                            0
Preferred Foot                 48
International Reputation       48
Weak Foot                      48
Skill Moves                    48
Work Rate                      48
Body Type                      48
Position                       60
Jersey Number                  60
Joined                       1553
Loaned From                 16943
Contract Valid Until          289
Height                         48
Weight                         48
Crossing                       48
Finishing                      48
HeadingAccuracy                48
ShortPassing                   48
Volleys                        48
Dribbling                      48
Curve                          48
FKAccuracy                     48
LongPassing                    48
BallControl                    48
Acceleration                   48
SprintSpeed                    48
Agility                        48
Reactions                      48
Balance                        48
ShotPower                      48
Jumping                        48
Stamina                        48
Strength                       48
LongShots                      48
Aggression                     48
Interceptions                  48
Positioning                    48
Vision                         48
Penalties                      48
Composure                      48
Marking                        48
StandingTackle                 48
SlidingTackle                  48
GKDiving                       48
GKHandling                     48
GKKicking                      48
GKPositioning                  48
GKReflexes                     48
Release Clause               1564
dtype: int64

In [19]:
(df.isna().sum()/len(df))*100

ID                           0.000000
Name                         0.000000
Age                          0.000000
Nationality                  0.000000
Overall                      0.000000
Potential                    0.000000
Club                         1.323667
Value                        0.000000
Wage                         0.000000
Preferred Foot               0.263635
International Reputation     0.263635
Weak Foot                    0.263635
Skill Moves                  0.263635
Work Rate                    0.263635
Body Type                    0.263635
Position                     0.329544
Jersey Number                0.329544
Joined                       8.529686
Loaned From                 93.057615
Contract Valid Until         1.587302
Height                       0.263635
Weight                       0.263635
Crossing                     0.263635
Finishing                    0.263635
HeadingAccuracy              0.263635
ShortPassing                 0.263635
Volleys                      0.263635
Dribbling                    0.263635
Curve                        0.263635
FKAccuracy                   0.263635
LongPassing                  0.263635
BallControl                  0.263635
Acceleration                 0.263635
SprintSpeed                  0.263635
Agility                      0.263635
Reactions                    0.263635
Balance                      0.263635
ShotPower                    0.263635
Jumping                      0.263635
Stamina                      0.263635
Strength                     0.263635
LongShots                    0.263635
Aggression                   0.263635
Interceptions                0.263635
Positioning                  0.263635
Vision                       0.263635
Penalties                    0.263635
Composure                    0.263635
Marking                      0.263635
StandingTackle               0.263635
SlidingTackle                0.263635
GKDiving                     0.263635
GKHandling                   0.263635
GKKicking                    0.263635
GKPositioning                0.263635
GKReflexes                   0.263635
Release Clause               8.590103
dtype: float64

In [20]:
df['Club'].isna().sum()

np.int64(241)

In [23]:
df['Club'] = df['Club'].fillna('Unknown')

In [24]:
df['Club'].isna().sum()

np.int64(0)

In [25]:
df['Preferred Foot'].isna().sum()

np.int64(48)

In [26]:
df['Preferred Foot'].fillna(df['Preferred Foot'].mode()[0],inplace=True)

In [27]:
df['Preferred Foot'].isna().sum()

np.int64(0)

In [31]:
df['International Reputation'].fillna(df['International Reputation'].mean(), inplace=True)

In [36]:
df['International Reputation'].isna().sum()

np.int64(0)

In [33]:
df['Weak Foot'].isna().sum()

np.int64(48)

In [37]:
df['Weak Foot']

0        4.0
1        4.0
2        5.0
3        3.0
4        5.0
        ...
18202    2.0
18203    2.0
18204    3.0
18205    3.0
18206    3.0
Name: Weak Foot, Length: 18207, dtype: float64

In [41]:
df['Weak Foot'].fillna(df['Weak Foot'].mean(), inplace=True)

In [42]:
df['Weak Foot'].isna().sum()

np.int64(0)

In [38]:
pd.set_option('display.max_columns', None)

In [40]:
df.sample(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
6999,169568,A. Hammill,30,England,68,68,St. Mirren,€850K,€4K,Right,1.0,4.0,4.0,Medium/ Medium,Lean,RS,77.0,"Oct 2, 2018",NaN,2019,5'10,163lbs,71.0,65.0,37.0,63.0,64.0,71.0,63.0,67.0,60.0,70.0,77.0,72.0,70.0,60.0,71.0,68.0,46.0,63.0,58.0,70.0,65.0,43.0,62.0,65.0,53.0,68.0,45.0,58.0,53.0,6.0,7.0,8.0,6.0,8.0,€1.5M
1080,201884,R. Brady,26,Republic of Ireland,77,78,Burnley,€10.5M,€52K,Left,1.0,3.0,4.0,High/ Medium,Normal,LWB,12.0,"Jan 31, 2017",NaN,2020,5'10,170lbs,80.0,70.0,59.0,72.0,66.0,78.0,81.0,79.0,75.0,76.0,79.0,78.0,74.0,74.0,76.0,78.0,73.0,74.0,64.0,75.0,58.0,66.0,73.0,77.0,72.0,74.0,63.0,68.0,71.0,12.0,8.0,13.0,7.0,7.0,€20.7M
13400,244575,A. Sánchez,19,Mexico,62,73,Cruz Azul,€450K,€2K,Right,1.0,3.0,2.0,Low/ High,Lean,CB,19.0,"Jul 1, 2018",NaN,2021,6'0,176lbs,30.0,29.0,68.0,48.0,26.0,45.0,28.0,33.0,33.0,39.0,62.0,59.0,47.0,47.0,59.0,44.0,73.0,76.0,74.0,29.0,45.0,54.0,25.0,32.0,39.0,54.0,66.0,62.0,68.0,9.0,14.0,7.0,11.0,9.0,€855K
6027,193900,J. Hunt,27,England,69,69,Bristol City,€875K,€18K,Right,1.0,2.0,3.0,High/ Medium,Lean,RB,32.0,"Jul 6, 2018",NaN,2021,5'9,157lbs,67.0,47.0,59.0,62.0,32.0,68.0,61.0,29.0,59.0,65.0,85.0,81.0,72.0,66.0,68.0,70.0,82.0,74.0,64.0,50.0,60.0,65.0,65.0,54.0,48.0,67.0,66.0,69.0,67.0,15.0,15.0,6.0,14.0,8.0,€1.7M
1890,183966,F. Roncaglia,31,Argentina,75,75,RC Celta,€4.5M,€20K,Right,2.0,3.0,2.0,Medium/ High,Normal,CB,24.0,"Jul 12, 2016",NaN,2020,5'10,168lbs,68.0,38.0,70.0,69.0,25.0,59.0,67.0,52.0,81.0,69.0,61.0,67.0,65.0,72.0,69.0,80.0,80.0,65.0,72.0,73.0,74.0,79.0,51.0,59.0,35.0,70.0,70.0,80.0,78.0,15.0,14.0,15.0,6.0,15.0,€9.4M